name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validation & Deployment
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-east-1" 
      AWS_PROFILE: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply (On Main Branch Only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
